services:
  db:
    image: postgres:latest
    container_name: oddhandyman-postgres
    environment:
      POSTGRES_DB: oddhandyman
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      JWT_SECRET: "${JWT_SECRET}"
    ports:
      - "5432:5432"
    volumes:
      - oddhandyman-data:/var/lib/postgresql   # named volume
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: oddhandyman-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/oddhandyman
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SERVER_PORT: ${SERVER_PORT}
      JWT_SECRET: "${JWT_SECRET}"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

# Declare all named volumes here
volumes:
  oddhandyman-data:
